language: node_js

cache:
  directories:
    - 'node_modules'

node_js:
  - '10'

before_install:
  - cd react
  - yarn add coveralls

install:
  - yarn install

script:
  - yarn test

after_success:
  - yarn test:coverage
